# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61udio_service.proto\x12\raudio_service\"0\n\x14GenerateAudioRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"[\n\x15GenerateAudioResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06s3_url\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x15\n\rerror_message\x18\x04 \x01(\t2j\n\x0c\x41udioService\x12Z\n\rGenerateAudio\x12#.audio_service.GenerateAudioRequest\x1a$.audio_service.GenerateAudioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GENERATEAUDIOREQUEST']._serialized_start=38
  _globals['_GENERATEAUDIOREQUEST']._serialized_end=86
  _globals['_GENERATEAUDIORESPONSE']._serialized_start=88
  _globals['_GENERATEAUDIORESPONSE']._serialized_end=179
  _globals['_AUDIOSERVICE']._serialized_start=181
  _globals['_AUDIOSERVICE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
