# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import audio_service_pb2 as audio__service__pb2


class AudioServiceStub(object):
    """Audio generation service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateAudio = channel.unary_unary(
                '/audio_service.AudioService/GenerateAudio',
                request_serializer=audio__service__pb2.GenerateAudioRequest.SerializeToString,
                response_deserializer=audio__service__pb2.GenerateAudioResponse.FromString,
                )


class AudioServiceServicer(object):
    """Audio generation service
    """

    def GenerateAudio(self, request, context):
        """Generate audio from text and return S3 URL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAudio,
                    request_deserializer=audio__service__pb2.GenerateAudioRequest.FromString,
                    response_serializer=audio__service__pb2.GenerateAudioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audio_service.AudioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AudioService(object):
    """Audio generation service
    """

    @staticmethod
    def GenerateAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/audio_service.AudioService/GenerateAudio',
            audio__service__pb2.GenerateAudioRequest.SerializeToString,
            audio__service__pb2.GenerateAudioResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
